#!/bin/bash
 
if [ $# -eq 0 ]; then
	python3 $(cd "$(dirname "$0")"; pwd)/show_smi.py
else
	python3 $(cd "$(dirname "$0")"; pwd)/show_smi.py $@ &
	PID1=$!
	 
	while kill -0 $PID1 2>/dev/null; do
	    read -s -n 1 key 
	    if [ "$key" = "q" ]; then
	         kill -9 $PID1
	         break
	    fi
	done
fi
